# Site settings
title: My Theme
email: itaouil@gmail.com
description: "Learner // Hussler // Undergrad"

# Build settings
markdown: kramdown
permalink: pretty

port: 8000

sass:
  sass_dir: assets/css
  style: :compressed
