# Portfolio settings
title: إلياس
email: itaouil95@gmail.com
kicker: Learner // Traveler // Software Engineer

# SEO section
seo:
  description: 'Freelancer, Freelancing, Software Developer, Software Engineer, Software, Full Stack, Artificial Intelligence, Machine Learning, Natural Language Processing, Java, JavaScript, NodeJS, AngularJS, HTML, CSS, SASS, Algorithms'
  rel-author: 'https://www.linkedin.com/in/ilyass-taouil-8b2b15a7/'
  rel-publisher: 'https://www.linkedin.com/in/ilyass-taouil-8b2b15a7/'

# Google Analytics
google-analytics-ua: UA-104783805-1

# Menu List
menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Experiences, url: '#experiences'}
- {name: Contact, url: '#contact'}

# Skill List
skills:
- {name: Communication, value: '7'}
- {name: Problem Solving, value: '6'}
- {name: Learning, value: '8'}
- {name: Creativity, value: '7'}
- {name: Design/UX, value: '5'}
- {name: Full Stack, value: '8'}
- {name: Artificial Intelligence, value: '7'}
- {name: Algorithms, value: '7'}

# Work List
projects:
- {name: Risotto POS System, folder: proj-1}
- {name: Portfolio Example, folder: proj-2}
- {name: JavaScript Mini Projects, folder: proj-3}
- {name: Deep Learning, folder: proj-4}
- {name: Morocco Tribute Page, folder: proj-5}
- {name: GitHub Profile Searcher, folder: proj-6}
- {name: Music Album, folder: proj-7}
- {name: Portfolio, folder: proj-8}

# Experiences List
experiences:
- {logo: 'caterva-logo.jpg', name: 'Caterva', title: 'Software Engineer', content: '<p>
  <strong>Software Engineer</strong> intern for a renewable energy startup in the south of Germany, Munich. My main task was to develop secure channels and interactive applications to respectively carry and display data related to the main product, the ESS. During the work placement I used different technologies and platforms, including JavaScript, NodeJS, AngularJS, HTML, SASS, CSS, Bash, Linux, RasbperryPi and other tools. Some of the projects I have worked on comprehend a data visualisation application, a REST API and a RasbperryPi based router interface.
</p>'}
- {logo: 'uol-logo.png', name: 'University Of Leeds', title: 'BSc, Computer Science with Artificial Intelligence', content: '<p>
  Currently in my last year of a <strong>Bachelor degree</strong> program with major in Artificial Intelligence. During the past two year spent at University I have tackled different courses ranging from cryptography, to networks to machine learning and in both years I have attained a 1st overall, respectively a 76% in my first year and 84% in my second one.
</p>'}
- {logo: 'funtech-logo.jpg', name: 'FunTech', title: 'Tutor', content: '<p>
  Interned as a tutor at a private institution focused on teaching children about the tech world. I personally taught three different classes including <strong>Java programming</strong>, <strong>Drone coding</strong> and <strong>Virtual Reality</strong>.
</p>'}

# Work List
social:
- {icon: 'icon-github.html', link: 'https://github.com/itaouil95/'}
- {icon: 'icon-twitter.html', link: 'https://twitter.com/itaouil95'}
- {icon: 'icon-linkedin.html', link: 'https://www.linkedin.com/in/ilyass-taouil-8b2b15a7/'}

# Default Images and Logos
logo: 'logo.html'
bg-img: 'vernazza.jpg'

avatar: 'avatar.png'
blurb: |
        <p>Hey there, <strong>my name is Ilyass</strong> and I am a final year Computer Science student at the <a href="https://www.leeds.ac.uk/" target="_blank">University Of Leeds</a>. My interests range from cool and momentarily useless <strong>Rasbperry PI, Full Stack and AI</strong> projects to more serious and pondered ones: <strong>My Final Year</strong>. Jokes apart, I am a <strong>driven</strong>, <strong>curios</strong>, <strong>well motivated</strong> and <strong>hard working</strong> person, who is craving to be part of great things and innovations in his lifetime. In the meanwhile, hit me up for some <a href="http://www.dictionary.com/browse/interesting?s=t" target="_blank">interesting</a> and <a href="http://www.dictionary.com/browse/challenging?s=t" target="_blank">challenging</a> <strong>freelancing/job/internship</strong> oppurtunities or just an orange juice, if you are in the surroundings (don't really fancy coffe, lol).</p>
