# Portfolio settings
title: إلياس
email: itaouil95@gmail.com
kicker: Undergrad // Traveler // Developer

# SEO section
seo:
  description: 'Freelancer, Freelancing, Software Developer, Software Engineer, Software, Full Stack, Artificial Intelligence, Machine Learning, Natural Language Processing, Java, JavaScript, NodeJS, AngularJS, HTML, CSS, SASS, Algorithms'
  rel-author: 'https://www.linkedin.com/in/ilyass-taouil-8b2b15a7/'
  rel-publisher: 'https://www.linkedin.com/in/ilyass-taouil-8b2b15a7/'

# Google Analytics
google-analytics-ua: UA-104783805-2

# Menu List
menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Experiences, url: '#experiences'}
- {name: Contact, url: '#contact'}

# Skill List
skills:
- {name: Communication, value: '7'}
- {name: Problem Solving, value: '5'}
- {name: Learning, value: '7'}
- {name: Creativity, value: '5'}
- {name: Design/UX, value: '3'}
- {name: Full Stack, value: '6'}
- {name: Artificial Intelligence, value: '5'}
- {name: Algorithms, value: '6'}

# Work List
projects:
- {name: Risotto POS System, folder: proj-1}
- {name: Portfolio, folder: proj-2}
- {name: JavaScript Mini Projects, folder: proj-3}
- {name: Ionic App, folder: proj-4}
- {name: Robotics Cluedo, folder: proj-5}
- {name: Object Detection, folder: proj-6}
- {name: Coming Soon, folder: proj-7}
- {name: Coming Soon, folder: proj-8}

# Experiences List
experiences:
- {logo: 'uol-logo.jpg', name: 'UoL RoboCup Team', title: 'Researcher & Developer', content: '<p>
  I am part of the RoboCup team supervised by Dr. Matteo Leonetti at the University of Leeds, where we tackle different Robotics tasks, ranging from navigation, vision and speech. I am part of the navigation team for which I am currently developing a <strong>ROS package</strong> (available from May on ROS) to estimate human pose in the environment (map). The package makes use of different tecniques, including deep Llearning for human detection on RGB data, point clouds for human-robot distance and leg detection algorithms for long distance detection and a more robust estimation.
</p>'}
- {logo: 'caterva-logo.jpg', name: 'Caterva', title: 'Software Engineer', content: '<p>
  <strong>Software Engineer</strong> intern for a renewable energy startup in the south of Germany, Munich. My main task was to develop secure channels and interactive applications to respectively carry and display data related to the main product, the ESS. During the work placement I used different technologies and platforms, including JavaScript, NodeJS, AngularJS, HTML, SASS, CSS, Bash, Linux, RasbperryPi and other tools. Some of the projects I have worked on comprehend a data visualisation application, a REST API and a RasbperryPi based router interface.
</p>'}
- {logo: 'uol-logo.jpg', name: 'University Of Leeds', title: 'BSc, Computer Science with Artificial Intelligence', content: '<p>
  Currently in my last year of a <strong>Bachelor degree</strong> program with major in Artificial Intelligence. During the past two year spent at University I have tackled different courses ranging from cryptography, to networks to machine learning and in both years I have attained a 1st overall, respectively a 76% in my first year and 84% in my second one.
</p>'}
- {logo: 'funtech-logo.jpg', name: 'FunTech', title: 'Tutor', content: '<p>
  Interned as a tutor at a private institution focused on teaching children about the tech world. I personally taught three different classes including <strong>Java programming</strong>, <strong>Drone coding</strong> and <strong>Virtual Reality</strong>.
</p>'}

# Work List
social:
- {icon: 'icon-github.html', link: 'https://github.com/itaouil95/'}
- {icon: 'icon-twitter.html', link: 'https://twitter.com/itaouil95'}
- {icon: 'icon-linkedin.html', link: 'https://www.linkedin.com/in/ilyass-taouil-8b2b15a7/'}

# Default Images and Logos
logo: 'logo.html'
bg-img: 'bg-hero.jpg'

avatar: 'avatar.jpg'
blurb: |
        <p>Hey there, <strong>my name is Ilyass</strong> and I am a final year Computer Science with Artificial Intelligence student at the <a href="https://www.leeds.ac.uk/" target="_blank">University Of Leeds</a>, graduating this May, after which I will be joining an MSc programme to deepen my understanding in Robotics. My current interests consist in <strong>Full Stack and AI (Machine Learning, Robotics)</strong> development, in fact, I am currently in the last stage of development of an <strong>open-source ROS package</strong> for human pose estimation in the environment. In my free time I like to travel and practice sport. I think of myself as <strong>driven</strong>, <strong>curios</strong>, <strong>well motivated</strong> and <strong>hard working</strong> person, willing to be part of something big. Oh yeah, I forgot to say that my dream is to <strong>Spaceflight</strong>. <a href="#contact">Yours ?</a>
